language: cpp

compiler:
    - gcc
    - clang

before_script:
    - sudo apt-get update
    - python -V
    - sudo apt-get install -y python3-pip
    - pip install conan
    - conan install .. --build cppunit
    - mkdir build
    - cd build
    - cmake ..

script: make